blur:
	{
		method = "gaussian";
		size = 4;
		deviation = 2.5;
	}
rules: (
	{
		blur-background = false;
		fade = false;
	},
	{
		match = "window_type = 'normal';
@include "anim.conf"
		fade = true;
		shadow = true;
	},
	{
		match = "window_type = 'dialog'";
		fade = true;
		shadow = true;
	},
	{
		match = "fullscreen" ||
			"class_g = retroarch'";
		corner-radius = 0;
		shadow = false;
	},
	{
		match = "window_type = 'dropdown_menu' || "
			"window_type = 'menu' || "
			"window_type = 'popup' || "
			"window_type = 'popup_menu' || "
			"window_type = 'tooltip'";
		corner-radius = 0;
		opacity = 0.95;
	},
	{
# Fix shadow related bugs on small UI elements
		match = "window_type = 'menu' || "
			"role = 'popup' || "
			"role = 'bubble' || "
			"class_i = 'xfce4-notifyd' || "
			"class_i = 'xfce4-screenshooter' || "
			"window_type = 'combo' || "
			"window_type = 'tooltip' || "
			"window_type = 'dock'";
		shadow = false;
	},
)
