Synaptic "" {
  packageColumnWidth "200";
  instVerColumnWidth "130";
  availVerColumnWidth "130";
  ViewMode "0";
  showWelcomeDialog "0";
  vpanedPos "233";
  hpanedPos "200";
  windowWidth "923";
  windowHeight "728";
  windowX "0";
  windowY "0";
  ToolbarState "2";
  Maximized "1";
  Install-Recommends "0";
};

