# ~/.config/pipewire/pipewire.conf.d/99-lowlatency.conf
context.properties = {
    # Lock the default rate to 48kHz
default.clock.rate          = 48000
# but allow these
default.clock.allowed-rates = [ 48000 44100 96000 192000 ]
    
    # 1024 is too high for gaming. Let's bound the dynamic quantum:
    # 64 samples  = ~1.3ms latency (Great for rhythm games / pro audio)
    # 128 samples = ~2.6ms latency (The sweet spot for performance vs. safety)
    # 512 samples = ~10.6ms latency (Maximum buffer fallback under heavy system load)
    default.clock.quantum       = 128
    default.clock.min-quantum   = 64
    default.clock.max-quantum   = 512
}

stream.properties = {
   # 4 is default, 10 is very high quality 14 is absolute max.
    resample.quality      = 7
}
