general {
	grab_focus = true
	}
cache {
	enabled = true
	}
finders {
	default_finder = desktop # math, desktop, unicode 
	desktop_launch_prefix = app2unit --
	desktop_icons = true
	}
ui {
	window_size = 300 300
	}
	
