

wallpaper {
    monitor =  DP-1
    path = $HOME/pictures/hyprwallpaper/
    fit_mode = cover
    timeout = 250
    order = random
}
wallpaper {
    monitor =  DVI-D-1
    path = $HOME/pictures/hyprwallpaper/
        fit_mode = cover
        timeout = 300
        order = random
}
splash = false
ipc = true
