# Theme: Catppuccin Mocha
# Soothing pastel theme for the high-spirited!

[Colors]
bg_color = #1E1E2ED1
text_color = #CDD6F4FF
accent_color = #CBA6F7FF
border_color = #31324499
badge_color = #F38BA8FF
badge_text_color = #11111BFF
hold_badge_color = #89B4FAFF
