# Theme: Nord
# An arctic, north-bluish color palette.

[Colors]
bg_color = #2E3440D1
text_color = #ECEFF4FF
accent_color = #81A1C1FF
border_color = #4C566A99
badge_color = #BF616AFF
badge_text_color = #ECEFF4FF
hold_badge_color = #88C0D0FF
