# Theme: Solarized Dark
# Precision colors for machines and people.

[Colors]
bg_color = #002B36D1
text_color = #839496FF
accent_color = #268BD2FF
border_color = #07364299
badge_color = #DC322FFF
badge_text_color = #FDF6E3FF
hold_badge_color = #2AA198FF
