#
# Select which emulator to run by setting the MODEL to one
# of the following:
#
# hp35|hp45|hp55|hp70|hp80|hp21|hp22|hp25|
# hp25c|hp27|hp29c|hp67|hp31e|hp32e|hp33e|hp33c|
# hp34c|hp37e|hp38e|hp38c|hp10c|hp11c|hp12c|hp15c|
# hp16c|hp10

MODEL="hp35"
OPTIONS=""

#
# To see a list of possible options define the default model above
# and use: (eventual paths must be absolute)
#
# 'bin/x11-calc --help'
#

