wireplumber.profiles = {
  ## Syntax:
  ## <profile> = {
  ##   inherits = [ other, profile, names ]   # optional
  ##   # optional is the default
  ##   <feature name> = [ required | optional | disabled ]
  ##   ...
  ## }

  # The default profile
  main = {
    inherits = [ base ]
    
    monitor.bluez = disabled
    monitor.bluez-midi = disabled
  }
}
