# common BT
blacklist btusb
blacklist bnep 
blacklist bluetooth
blacklist rfcomm

# realtek
blacklist btrtl 
# mediatek
blacklist btmtk 
# broadcom
blacklist btbcm 
# intel 
blacklist btintel








