.TH GSR-UI 1 "2024-08-01" "gsr-ui" "User Commands"
.SH NAME
gsr-ui \- A fullscreen overlay UI for GPU Screen Recorder in the style of ShadowPlay
.SH DESCRIPTION
\fBgsr-ui\fP is a fullscreen overlay UI for GPU Screen Recorder in the style of ShadowPlay.
The application is currently primarily designed for X11 but it can run on Wayland as well through XWayland, with some caveats because of Wayland limitations.
.PP
This interface is built mainly for use with keyboard shortcuts.
When launched for the first time, it runs in the background, ready to receive shortcut keys.
On a subsequent launch, the fullscreen overlay UI appears.
.SH AUTHORS
This manual page was written by the Debian team.
.SH REPORTING BUGS
Report bugs to:
.UR mailto:dec05eba@protonmail.com
dec05eba@protonmail.com
.UE .
.br
Please take a look at the FAQ part of the README before reporting a bug: \fIhttps://git.dec05eba.com/gpu-screen-recorder-ui/about\fR.
.SH COPYRIGHT
Copyright \(co dec05eba. Licensed under GPL-3.0-only.
.SH SEE ALSO
.UR https://git.dec05eba.com/gpu-screen-recorder-ui
Project homepage
.UE
.br
.UR https://git.dec05eba.com/gpu-screen-recorder
GPU Screen Recorder homepage (CLI)
.UE
.br
.BR gpu-screen-recorder (1),
.BR gsr-ui-cli (1)
