[General]
MaximizeOnStartup=true
RecentFiles=/mnt/500G/torrents/L'Entourloop - 2017 - Le Savoir Faire/folder.jpg, /mnt/500G/torrents/L'Entourloop - 2017 - Le Savoir Faire/cover.png, /home/daniel/downloads/czkawka/czkawka_gui/icons/icon.ico
SaveFolder=/mnt/500G/torrents/L'Entourloop - 2017 - Le Savoir Faire
mainWindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x1\0\0\0\x1\0\0\0\xa0\0\0\x3n\xfc\x2\0\0\0\x2\xfb\0\0\0$\0\x64\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\0_\0p\0\x61\0l\0\x65\0t\0t\0\x65\x1\0\0\0\x64\0\0\x1\x90\0\0\x1\x90\0\0\x1\x90\xfb\0\0\0$\0\x64\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\0S\0\x65\0t\0t\0i\0n\0g\0s\x1\0\0\x1\xf4\0\0\x1\xde\0\0\0\xae\0\0\x1\x90\0\0\x3\x94\0\0\x3n\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x2\0\0\0\x2\0\0\0\x1\0\0\0\x16\0m\0\x61\0i\0n\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x2\0\0\0\x1\0\0\0\xe\0t\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
primaryColor=#000000
secondaryColor=#ff0000
selectedTool=pointer
unit=0

[NewDialog]
resizeUnit=0

[toolSettings]
blur\pressure=10
blur\radius=10
eraser\radius=10
line\antialias=false
line\arrowStyle=0
line\opacity=100
line\style=0
line\width=1
magicWand\color=false
magicWand\tolerance=15
paintBrush\antialiasing=false
paintBrush\pressure=50
paintBrush\roundCap=true
paintBrush\width=5
paintBrushAdv\brushType=0
paintBrushAdv\fade=false
paintBrushAdv\pressure=10
paintBrushAdv\step=1
pointer\fill=false
pointer\selection=rect
pointer\stroke=false
pointer\strokeWidth=1
smudge\pressure=10
smudge\radius=10
sprayCan\dispersion=50
sprayCan\pressure=10
sprayCan\radius=10
sprayCan\rainbow=false
stamp\diffuse=false
stamp\fixed=false
stamp\precise=false
stamp\pressure=10
stamp\radius=10
stamp\step=1
